blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.index, name='home'),
    path('search/',views.search_results, name='search_results'),
    # View thinkpieces
    path('thinkpieces/', views.ThinkpieceList.as_view(), name='thinkpieces'),
    path('thinkpieces/<slug:slug>/', views.ThinkpieceDetail.as_view(), 
         name='thinkpiece_detail'),
    # View Breakdowns
    path('bill_breakdowns/', views.bill_breakdowns, name='bill_breakdowns'),
    path('bill_breakdowns/<slug:slug_text>/',views.bill_breakdown,
         name='bill_breakdown'),
    path('bill_breakdowns/<slug:slug_text>/<int:pic_id>/',
         views.pics,name='pics'),
     
    #Wastebooks 
    path('wastebooks/', views.wastebooks, name='wastebooks'), 
    path('new-wastebook/', views.new_wastebook, name='new_wastebook'),
    path('wastebooks/<int:id>/edit', views.edit_wastebook, name='edit_wastebook'),
    path('wastebooks/<int:id>/delete', views.delete_wastebook, name='delete_wastebook'),

    


    # Roundup
    path('roundups/',views.RoundupList.as_view(),name='roundups'),
    path('roundups/<slug:slug>/', views.RoundupDetail.as_view(), 
         name='roundup_detail'),
      
    # Backend
    path('admin_main/', views.admin_main, name='admin_main'),
    
    # Thinkpieces
    path('new_thinkpiece/', views.new_thinkpiece, name='new_thinkpiece'),
    path('thinkpieces/<slug:slug>/edit', views.edit_thinkpiece, 
         name='edit_thinkpiece'),
    path('thinkpieces/<slug:slug>/delete', views.delete_thinkpiece, 
         name='delete_thinkpiece'),
    
    
    # Roundups
    path('new_roundup/', views.new_roundup, name='new_roundup'),
    path('roundup/<slug:slug>/edit', views.edit_roundup, 
         name='edit_roundup'),
    path('roundup/<slug:slug>/delete', views.delete_roundup, 
         name='delete_roundup'),
    
    # Bill Breakdowns
    path('new_bill_breakdown/', views.new_bill_breakdown, 
         name='new_bill_breakdown'),
    path('edit/bill_breakdowns/<slug:slug_text>', views.edit_breakdown_view,
         name='edit_breakdown_view'),
    path('new_detail/bill_breakdowns/<slug:slug_text>/', 
         views.new_breakdown_detail, name='new_breakdown_detail'),
    path('edit/bill_breakdowns/<slug:slug_text>/', views.edit_breakdown_head,
         name='edit_breakdown_head'),
    path('edit/bill_breakdowns/<slug:slug_text>/<int:breakdownitem_id>/', 
         views.edit_breakdown_detail,name='edit_breakdown_detail'),
    path('delete/bill_breakdowns/<slug:slug_text>/', views.delete_breakdown, 
         name='delete_breakdown'),
    path('delete/bill_breakdowns/<slug:slug_text>/<int:breakdownitem_id>/', 
         views.delete_breakdown_detail, name='delete_breakdown_item'),
    path('donate/',views.donate, name='donate'),

    

    ]

rando_land/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('django.contrib.auth.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),name='password_reset_complete'),
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name="registration/password_change.html"), name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"), name='password_change_done'),
    path('users/',include('users.urls')),
    path('', include('blog.urls')),
    path('wastebooks/', include('wastebooks.urls')),

    
]

#if settings.DEBUG:  # Dev only
#    urlpatterns += static(settings.STATIC_URL,
#                          document_root=settings.STATIC_ROOT)
#    urlpatterns += static(settings.MEDIA_URL,
#                          document_root=settings.MEDIA_ROOT)

wastebooks/urls.py
from django.urls import path
from . import views

app_name = 'wastebooks'

urlpatterns = [
    # HEERF 
    path('heerf/', views.heerf, name='heerf'),
    path('heerf-state/', views.heerf_state, name='heerf_main'),
    path('heerf-inst/', views.heerf_inst, name='heerf_lookup'),
    path('svog/', views.svog, name='svog'),
    path('svog_state/', views.svog_state, name='svog_state'),
    path('svog_city/', views.svog_city, name='svog_city'),
    path('svog_venue/', views.svog_venue, name='svog_venue'),
    ]

wastebooks/models.py
from django.db import models

# Create your models here.

wastebooks/views.py
from django.shortcuts import render
import pandas as pd
import numpy as np
import json

# Create your views here.

#HEERF


def heerf(request):
    heerf_csv=pd.read_csv('https://raw.githubusercontent.com/oilfieldrando/HEERF_final/main/heerf_final2.csv')
    states=['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Marshall Islands', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Mariana Islands', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Virgin Islands', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia','Wyoming','Wisconsin','Palau']
    state_name=request.POST.get('inputState')
    
    

    if request.POST.get('chart_view'):
        chart_view = request.POST.get('chart_view')
        if request.POST.get('chart_view')=='Totals by State':
            view_type='chart1'
            

        elif request.POST.get('chart_view')=='50 Biggest Payouts':
            view_type='chart2'

        elif request.POST.get('chart_view')=='50 Richest Colleges':
            view_type='chart3'
    else:
        chart_view = 'Totals by State'
        view_type = 'chart1'
    
    if request.POST.get('view_type1'):
        chart_view = 'Totals by State'
        view_type = request.POST.get('view_type1')

    elif request.POST.get('view_type2'):
        chart_view = '50 Biggest Payouts'
        view_type = request.POST.get('view_type2')

    elif request.POST.get('view_type3'):
        chart_view = '50 Richest Colleges'
        view_type = request.POST.get('view_type3')

    else: 
        if chart_view == 'Totals by State':
            view_type = 'chart1'
        elif chart_view == '50 Biggest Payouts':
            view_type = 'chart2'
        else:
            view_type = 'chart3'

    
    inst_name=request.POST.get('inputInst')  
    heerf_csv.sort_values(by=['institution'], inplace=True, ascending=True)
    inst_list=heerf_csv[heerf_csv['state_full']==state_name][heerf_csv.columns[1]].tolist()
    inst_count=len(inst_list)

    
    # Relief by State
    
    state_totals = pd.DataFrame({'state':[],'cares_act':[],'omnibus':[],'amer_rescue_act':[],'total_relief':[]})
    for x in states:
        state_data=heerf_csv[heerf_csv['state_full']==x]
        state_totals=state_totals.append({'state':x,'cares_act':state_data.iloc[:,[3]].sum(),'omnibus':state_data.iloc[:,[4]].sum(),'amer_rescue_act':state_data.iloc[:,[5]].sum(),'total_relief':state_data.iloc[:,[6]].sum()}, ignore_index=True)
        state_totals=state_totals.astype({"total_relief":'float',"cares_act":'float',"omnibus":'float',"amer_rescue_act":'float'})
        state_totals=state_totals.sort_values(by='total_relief',ascending=False)    
        state_labels = list(state_totals['state'].values)
        state_cares = list(state_totals['cares_act'].values)
        state_omnibus = list(state_totals['omnibus'].values)
        state_ara = list(state_totals['amer_rescue_act'].values)
        total_relief = list(state_totals['total_relief'].values)
        
        
    allData=[]
    for i in range(state_totals.shape[0]):
        temp=state_totals.loc[i]
        allData.append(dict(temp))


    # Top Recipients
    heerf_csv.sort_values(by=['total_relief'],inplace=True,ascending=False)
    top50 = heerf_csv.iloc[:50]
    t50_labels = top50['institution'].values.tolist()
    t50_cares = top50['cares_act'].values.tolist()
    t50_omnibus = top50['omnibus'].values.tolist()
    t50_ara = top50['amer_rescue_act'].values.tolist()
    t50_total = top50['total_relief'].values.tolist()

    top50_data = []
    for i in range(top50.shape[0]):
        temp=top50.loc[i]
        top50_data.append(dict(temp))

    # Rich Recipients
    
    heerf_csv.sort_values(by=['endowment'],inplace=True,ascending=False)
    rich50 = heerf_csv.iloc[:50].reset_index()
    rich50_labels = rich50['institution'].values.tolist()
    rich50_cares = rich50['cares_act'].values.tolist()
    rich50_omnibus = rich50['omnibus'].values.tolist()
    rich50_ara = rich50['amer_rescue_act'].values.tolist()
    rich50_total = rich50['total_relief'].values.tolist()

    rich50_data = []
    for i in range(rich50.shape[0]):
        temp2=rich50.loc[i]
        rich50_data.append(dict(temp2))
    
     
    context={
        'inst_list':inst_list,
        'state_name':state_name,
        'data':allData,
        'states':states, 
        'state_labels':state_labels,
        'total_relief':total_relief, 
        'state_cares':state_cares, 
        'state_omnibus':state_omnibus,
        'state_ara':state_ara,
        't50_labels':t50_labels,
        't50_cares':t50_cares,
        't50_omnibus':t50_omnibus,
        't50_ara':t50_ara,
        't50_total':t50_total,
        'top50_data':top50_data,
        'rich50_data':rich50_data,
        'rich50_labels':rich50_labels,
        'rich50_cares':rich50_cares,
        'rich50_omnibus':rich50_omnibus,
        'rich50_ara':rich50_ara,
        'rich50_total':rich50_total,
        'chart_view':chart_view,
        'view_type':view_type,
        
        }
    return render(request,'heerf.html',context)

def heerf_state(request):
    # Lookup Bars
    states=['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Marshall Islands', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Mariana Islands', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Virgin Islands', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia','Wyoming','Wisconsin','Palau']
    
    if request.POST.get('inputState'):
        state_name=request.POST.get('inputState')
    else:
        state_name='Alabama'
    inst_name=request.POST.get('inputInst')
    heerf_csv=pd.read_csv('https://raw.githubusercontent.com/oilfieldrando/HEERF_final/main/heerf_final2.csv')  
    heerf_csv.sort_values(by=['institution'], inplace=True, ascending=True)
    inst_list=heerf_csv[heerf_csv['state_full']==state_name][heerf_csv.columns[1]].tolist()
    inst_count=len(inst_list)
    
    

    # State totals graph
    state_totals = pd.DataFrame({'state':[],'cares_act':[],'omnibus':[],'amer_rescue_act':[],'total_relief':[]})
    for x in states:
        state_data=heerf_csv[heerf_csv['state_full']==state_name]
        state_totals=state_totals.append({'state':x,'cares_act':state_data.iloc[:,[3]].sum(),'omnibus':state_data.iloc[:,[4]].sum(),'amer_rescue_act':state_data.iloc[:,[5]].sum(),'total_relief':state_data.iloc[:,[6]].sum()}, ignore_index=True)
        state_totals=state_totals.astype({"total_relief":'float',"cares_act":'float',"omnibus":'float',"amer_rescue_act":'float'})
        state_totals=state_totals.sort_values(by='total_relief',ascending=False) 
    state_detail = pd.DataFrame(state_totals[state_totals['state']==state_name][state_totals.columns[0:]])
    
    cares=state_detail.iloc[0,1]
    omnibus=state_detail.iloc[0,2]
    ara=state_detail.iloc[0,3]
    state_total=state_detail.iloc[0,4]


    # Institution Table
    
    heerf_csv.sort_values(by=['total_relief'], inplace=True, ascending=False)
    inst_data = heerf_csv[heerf_csv['state_full']==state_name].iloc[0:].reset_index()
    inst_data = inst_data.astype({"total_relief":'float'})
    
    inst_set = []
    for i in range(inst_data.shape[0]):
        temp1=inst_data.loc[i]
        inst_set.append(dict(temp1))

    inst_code_set = []
    heerf_csv.sort_values(by=['institution'], inplace=True, ascending=True)
    inst_data2 = heerf_csv[heerf_csv['state_full']==state_name].iloc[0:].reset_index()
    
    for i in range(inst_data2.shape[0]):
        temp2=inst_data2.loc[i]
        inst_code_set.append(dict(temp2))

    # Inst graph
    inst_df=pd.DataFrame(heerf_csv[heerf_csv['state_full']==state_name])
    inst_df.columns=['inst_st','inst','inst_state','inst_cares','inst_omnibus','inst_ara','inst_total','endowment','code']
    inst_labels=inst_df['inst'].values.tolist()
    inst_totals=inst_df['inst_total'].values.tolist()
    
    context={
        'states':states,
        'state_name':state_name,
        'inst_list':inst_list,
        'inst_name':inst_name,
        'state_detail':state_detail,
        'cares':cares,
        'omnibus':omnibus,
        'ara':ara,
        'state_total':state_total,
        'inst_set':inst_set,
        'inst_labels':inst_labels,
        'inst_totals':inst_totals,
        'inst_count':inst_count,
        'inst_code_set':inst_code_set 
    }
    return render(request, 'heerf_main.html', context)

def heerf_inst(request):
    heerf_csv=pd.read_csv('https://raw.githubusercontent.com/oilfieldrando/HEERF_final/main/heerf_final2.csv')

    # Inputs

templates/breakdown_detail.html
{% extends "base.html" %}
{% load static %}

{% block tags %}
<!-- Primary Meta Tags -->
<title>{{bill_breakdown.title}}</title>
<meta name="title" content="{{bill_breakdown.title}}">
<meta name="description" content="Mucking through .gov so you don't have to.">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://www.randoland.us/bill_breakdowns/{{bill_breakdown.slug}}">
<meta property="og:title" content="Breakdown: {{bill_breakdown.title}}">
<meta property="og:description" content="{{bill_breakdown.blurb}}">
<meta property="og:image" content="https://d3346f13f1pt3f.cloudfront.net/static/logolarge.png">

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:url" content="https://www.randoland.us/bill_breakdowns/{{bill_breakdown.slug}}">
<meta name="twitter:title" content="Breakdown: {{bill_breakdown.title}}">
<meta name="twitter:description" content="{{bill_breakdown.blurb}}">
<meta name="twitter:image" content="{{bill_breakdown.image.url}}">

{% endblock tags %}

{% block page_header %}


<div class="row">
  <div class="col text-left">
    <a href="{% url 'blog:bill_breakdowns' %}" class="btn btn-secondary">&laquo;Breakdowns</a>
  </div>
  <div class="col text-right">
    <a href="https://www.facebook.com/sharer.php?u=https://www.randoland.us/bill_breakdowns/{{bill_breakdown.slug}}" class="btn btn-primary"> 
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
      </svg>&nbsp;Share
    </a>
    <a href="https://twitter.com/share?url=https://www.randoland.us/bill_breakdowns/{{bill_breakdown.slug}}&text=Rando's Breakdown of {{bill_breakdown.title}}" class="btn btn-primary">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
      </svg>&nbsp;Share
    </a>
  </div>  
</div>
{% endblock page_header %}


{% block content %}

<div class="card mb-3 p-3">
  <img class="card-img-top" src="{{bill_breakdown.image.url}}" alt="Card image cap">
  <div class="card-body">
    <h4 class="card-title mb-2">{{bill_breakdown.title}}<br>
    
      <a href="{{bill_breakdown.bill_link}}">
        <small class="text-muted">Link &raquo;</small>       
      </a>
    </h4>
    <div class="pb-2 mb-2 border-bottom"></div>
    {% for breakdownitem in breakdownitems %} 
    <a class="text-dark" href="{% url 'blog:pics' bill_breakdown.slug breakdownitem.id %}">
    <h5 class="card-subtitle mt-3">{{breakdownitem.title}}</h5>
    </a>

     <p class="card-text mb-3">{{breakdownitem.text|safe}}</p>
    {% endfor %}
  
    <div class="container-fluid pt-2">
      <a href="https://www.facebook.com/sharer.php?u=https://www.randoland.us/bill_breakdowns/{{bill_breakdown.slug}}" class="btn btn-primary"> 
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
          <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
        </svg>&nbsp;Share
      </a>
      <a href="https://twitter.com/share?url=https://www.randoland.us/bill_breakdowns/{{bill_breakdown.slug}}&text=Rando's Breakdown of {{bill_breakdown.title}}" class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
          <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </svg>&nbsp;Share
      </a>
    </div>
  </div>
</div>
{% endblock content %}

templates/edit_roundup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<p> 
    <a href="{% url 'blog:admin_main' %}">Back to admin</a>
</p>
    <h4>Edit Roundup</h4>
{% endblock page_header %}

{% block content %}

<form method="post" action="{% url 'blog:edit_roundup' roundup.slug %}" enctype="multipart/form-data" class="form">
    {% csrf_token %}
    {{form.media}}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">Update</button>
    {% endbuttons %}
    
</form>



{% endblock content %}

templates/edit_thinkpiece.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<p> 
    <a href="{% url 'blog:admin_main' %}">Back to admin</a>
</p>

    <h4>Edit Thinkpiece</h4>
{% endblock page_header %}

{% block content %}

<form method="post" action="{% url 'blog:edit_thinkpiece' thinkpiece.slug %}" enctype="multipart/form-data" class="form">
    {% csrf_token %}
    {{form.media}}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">Update</button>
    {% endbuttons %}
    
</form>



{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block tags %}
<!-- Primary Meta Tags -->
<title>RandoLand</title>
<meta namne="title" content="Latest Posts">
<meta name="description" content="Mucking through .gov so you don't have to.">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://www.randoland.us/">
<meta property="og:title" content="Latest Posts">
<meta property="og:description" content="Mucking through .gov so you don't have to.">
<meta property="og:image" content="https://d3346f13f1pt3f.cloudfront.net/static/logolarge.png">

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:url" content="https://www.randoland.us/">
<meta name="twitter:title" content="Latest Posts">
<meta name="twitter:description" content="Mucking through .gov so you don't have to.">
<meta name="twitter:image" content="https://d3346f13f1pt3f.cloudfront.net/static/logolarge.png">
{% endblock tags %}

{% block page_header %}

{% comment %}
<div class="text-center">
    <h3>Latest Posts</h3>
</div>
{% endcomment %}

{% endblock page_header %}

{% block content %}
<style>
  a:hover
  {text-decoration:none;}
  .card:hover{
  box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
}
</style>

<h5>
  <a class="text-dark" href="{% url 'blog:bill_breakdowns' %}">Breakdowns&raquo;</a>
</h5>

{% for bill_breakdown in bill_breakdowns %}
  
  <div class="card mb-3 p-2 bg-light">
      <a href="{% url 'blog:bill_breakdown' bill_breakdown.slug %}">
      <div class="row no-gutters align-items-center">
        <div class="col-md-4">
          <img src="{{bill_breakdown.image.url}}" class="card-img" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title text-dark">{{bill_breakdown.title}}</h5>
            <p class="card-text text-dark">{{bill_breakdown.blurb}}</p>
          </div>
        </div>
      </div>
      </a>
  </div>   
{% empty %}
  <h3>No posts have been added yet</h3>
{% endfor %}

<h5>
  <a class="text-dark" href="{% url 'blog:wastebooks' %}">Dashboards&raquo;</a>
</h5>
{% for wastebook in wastebooks %}
  
  <div class="card mb-3 p-2 bg-light">
      <a href="{{wastebook.url}}">
      <div class="row no-gutters align-items-center">
        <div class="col-md-4">
          <img src="{{wastebook.image.url}}" class="card-img" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title text-dark">{{wastebook.title}}</h5>
            <p class="card-text text-dark">{{wastebook.desc}}</p>
          </div>
        </div>
      </div>
      </a>
  </div>   
{% empty %}
  <h3>No posts have been added yet</h3>
{% endfor %}

<h5>
  <a class="text-dark" href="{% url 'blog:thinkpieces' %}">Thinkpieces&raquo;</a>
</h5>

{% for thinkpiece in thinkpieces %}

<div class="card mb-3 p-2 bg-light">
  <a href="{% url 'blog:thinkpiece_detail' thinkpiece.slug %}">
  <div class="row no-gutters align-items-center">
    <div class="col-md-4">
      <img src="{{thinkpiece.image.url}}" class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title text-dark">{{thinkpiece.title}}</h5>
        <p class="card-text text-dark">{{thinkpiece.blurb}}</p>
      </div>
    </div>
  </div>
  </a>
</div>
{% empty %}
  <h3>No posts have been added yet</h3>
{% endfor %}

{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
    {% if message.tags %}<div class="alert alert-{{
     message.tags }}">{{message}}</div>{% endif %}
    {% endfor %}
{% endif %}

templates/new_bill_breakdown.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<p> 
    <a href="{% url 'blog:admin_main' %}">Back to admin</a>
</p>
    <h4>New Breakdown</h4>
{% endblock page_header %}

{% block content %}

<form method="post" action="{% url 'blog:new_bill_breakdown' %}" enctype="multipart/form-data" class="form">
    {% csrf_token %}
    {{form.media}}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
    
</form>



{% endblock content %}

templates/new_roundup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<p> 
    <a href="{% url 'blog:admin_main' %}">Back to admin</a>
</p>
    <h4>New Roundup</h4>
{% endblock page_header %}

{% block content %}

<form method="post" action="{% url 'blog:new_roundup' %}" enctype="multipart/form-data" class="form">
    {% csrf_token %}
    {{form.media}}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
    
</form>



{% endblock content %}