blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.index, name='home'),
    path('search/',views.search_results, name='search_results'),
    # View thinkpieces
    path('thinkpieces/', views.ThinkpieceList.as_view(), name='thinkpieces'),
    path('thinkpieces/<slug:slug>/', views.ThinkpieceDetail.as_view(), 
         name='thinkpiece_detail'),
    # View Breakdowns
    path('bill_breakdowns/', views.bill_breakdowns, name='bill_breakdowns'),
    path('bill_breakdowns/<slug:slug_text>/',views.bill_breakdown,
         name='bill_breakdown'),
    path('bill_breakdowns/<slug:slug_text>/<int:pic_id>/',
         views.pics,name='pics'),
     
    #Wastebooks 
    path('wastebooks/', views.wastebooks, name='wastebooks'), 
    path('new-wastebook/', views.new_wastebook, name='new_wastebook'),
    path('wastebooks/<int:id>/edit', views.edit_wastebook, name='edit_wastebook'),
    path('wastebooks/<int:id>/delete', views.delete_wastebook, name='delete_wastebook'),

    


    # Roundup
    path('roundups/',views.RoundupList.as_view(),name='roundups'),
    path('roundups/<slug:slug>/', views.RoundupDetail.as_view(), 
         name='roundup_detail'),
      
    # Backend
    path('admin_main/', views.admin_main, name='admin_main'),
    
    # Thinkpieces
    path('new_thinkpiece/', views.new_thinkpiece, name='new_thinkpiece'),
    path('thinkpieces/<slug:slug>/edit', views.edit_thinkpiece, 
         name='edit_thinkpiece'),
    path('thinkpieces/<slug:slug>/delete', views.delete_thinkpiece, 
         name='delete_thinkpiece'),
    
    
    # Roundups
    path('new_roundup/', views.new_roundup, name='new_roundup'),
    path('roundup/<slug:slug>/edit', views.edit_roundup, 
         name='edit_roundup'),
    path('roundup/<slug:slug>/delete', views.delete_roundup, 
         name='delete_roundup'),
    
    # Bill Breakdowns
    path('new_bill_breakdown/', views.new_bill_breakdown, 
         name='new_bill_breakdown'),
    path('edit/bill_breakdowns/<slug:slug_text>', views.edit_breakdown_view,
         name='edit_breakdown_view'),
    path('new_detail/bill_breakdowns/<slug:slug_text>/', 
         views.new_breakdown_detail, name='new_breakdown_detail'),
    path('edit/bill_breakdowns/<slug:slug_text>/', views.edit_breakdown_head,
         name='edit_breakdown_head'),
    path('edit/bill_breakdowns/<slug:slug_text>/<int:breakdownitem_id>/', 
         views.edit_breakdown_detail,name='edit_breakdown_detail'),
    path('delete/bill_breakdowns/<slug:slug_text>/', views.delete_breakdown, 
         name='delete_breakdown'),
    path('delete/bill_breakdowns/<slug:slug_text>/<int:breakdownitem_id>/', 
         views.delete_breakdown_detail, name='delete_breakdown_item'),
    path('donate/',views.donate, name='donate'),

    

    ]

rando_land/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('django.contrib.auth.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),name='password_reset_complete'),
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name="registration/password_change.html"), name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"), name='password_change_done'),
    path('users/',include('users.urls')),
    path('', include('blog.urls')),
    path('wastebooks/', include('wastebooks.urls')),

    
]

#if settings.DEBUG:  # Dev only
#    urlpatterns += static(settings.STATIC_URL,
#                          document_root=settings.STATIC_ROOT)
#    urlpatterns += static(settings.MEDIA_URL,
#                          document_root=settings.MEDIA_ROOT)

wastebooks/urls.py
from django.urls import path
from . import views

app_name = 'wastebooks'

urlpatterns = [
    # HEERF 
    path('heerf/', views.heerf, name='heerf'),
    path('heerf-state/', views.heerf_state, name='heerf_main'),
    path('heerf-inst/', views.heerf_inst, name='heerf_lookup'),
    path('svog/', views.svog, name='svog'),
    path('svog_state/', views.svog_state, name='svog_state'),
    path('svog_city/', views.svog_city, name='svog_city'),
    path('svog_venue/', views.svog_venue, name='svog_venue'),
    ]

templates/svog/svog_city.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}
{% load humanize %}

{% block tags %}

<!-- Primary Meta Tags -->
<title>SVOG Dashboard</title>
<meta name="title" content="SVOG Dashboard">
<meta name="description" content="Shuttered Venue Operators Grantees">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://www.randoland.us/svog_city/">
<meta property="og:title" content="Wastebook: Shuttered Venue Operators Grants">
<meta property="og:description" content="Database of SVOG grantees">
<meta property="og:image" content="https://d3346f13f1pt3f.cloudfront.net/static/svog.png">

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:url" content="https://www.randoland.us/svog_city">
<meta name="twitter:title" content="Wastebook: Shuttered Venue Operators Grants">
<meta name="twitter:description" content="Database of SVOG grantees">
<meta name="twitter:image" content="https://d3346f13f1pt3f.cloudfront.net/static/svog.png">

{% endblock tags %}


{% block page_header %}

<div class="container-fluid">
  <div class="row">
  <div class="col-lg-6">
    <div class="text-left">
      <a href="{% url 'wastebooks:svog' %}">Dashboard Home</a>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="text-right">
      <a href = "https://data.sba.gov/dataset/svog">Data Source</a>
    </div>
  </div>
</div>

</div>

<div class="text-center container-fluid">
  <h2>Shuttered Venue Operators Grantees</h2>
</div>
{% endblock page_header %}  

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.1.1/dist/chart.min.js"></script>

<div class="container-fluid">
  <div class="row">
    <div class="col-auto">
      <form action="{% url 'wastebooks:svog_state' %}" method="post" id="inputState" >
      {% csrf_token %}
        <div class="form-group" style="max-width:200px">
          <label for="inputState" class="col-sm-2 col-form-label col-form-label-sm">State/Territory:</label>
            <select class="form-control form-control-sm" name="inputState" id="inputState" onchange="this.form.submit()">
              <option>{{state}}</option>
              {% for i in state_list %}
              <option>{{i}}</option>
              {% endfor %}
            </select>
        </div>
      </form>
    </div>
    
    <div class="col-auto"> 
      <form method="post" action="{% url 'wastebooks:svog_city' %}" id="inputCity">
          {% csrf_token %}
          <div class="form-group" style="max-width:400px">
            <label for="inputCity" class="col-sm-2 col-form-label col-form-label-sm">City:</label>
                  <select class="form-control form-control-sm" name="inputCity" id="inputCity" onchange="this.form.submit()">
                      <option>{{city_name}}</option>
                      {% for i in city_list %}
                      <option value="{{i.city_id}}">{{i.city}}</option>
                      {% endfor %}
                  </select>
          </div>
      </form>
    </div>
    <div class="col-auto"> 
      <form method="post" action="{% url 'wastebooks:svog_venue' %}" id="inputVenue" >
          {% csrf_token %}
          <div class="form-group" style="max-width:400px">
            <label for="inputVenue" class="col-sm-2 col-form-label col-form-label-sm">Venue:</label>
                  <select class="form-control form-control-sm" name="inputVenue" id="inputVenue" onchange="this.form.submit()">
                      <option class="text-center" value="" selected disabled>--select venue--</option>
                      {% for i in venue_list_data %}
                      <option value="{{i.inst_id}}">{{i.venue}}</option>
                      {% endfor %}
                  </select>
          </div>
      </form>
    </div>
    
  </div>
</div>

<div class="border-bottom"></div>

<div class="pt-2 pb-4 container">
  <div class="container-fluid pb-4">
    <div class= "text-center">
      <h2>{{city_name}}</h2>
    </div>
    <table class="m-auto text-center mt-2 table table-bordered" style="max-width:600px;">
      <tr>
      </tr>
      <tbody class="thead-dark">
        <tr class="table-active">
          <th scope="row" class="align-middle">Total Grants</th>
          <td class="text-center align-middle"><b>${{city_total|floatformat:0|intcomma}}</b></td>               
        </tr>
        <tr class="table-active">
          <th scope="row" class="align-middle">Recipients</th>
          <td class="text-center align-middle"><b>{{city_grantees|floatformat:0|intcomma}}</b></td>               
        </tr>
      </tbody>
    </table>
  </div>
  <div class="text-center">
    <h4>Venue Payouts</h4>
  </div>
  <div class="table-responsive table-striped">
    <table class="m-auto text-center mt-2 table table-sm table-bordered" style="max-width:600px">
      <thead class="thead-dark">
        <tr>
          <th class="text-center align-middle" scope="col">Venue</th>
          <th scope="col" class="text-center align-middle">Grant Total</th>
            </tr>
      </thead>
          <tbody>
            {% for i in venues_desc_data %}
            <tr>
              <td class="text-center align-middle">
                <form action="{% url 'wastebooks:svog_venue' %}"  method="post">
                {% csrf_token %}
                  <button type="submit" name="inputVenue" value="{{i.inst_id}}" class="btn btn-sm btn-light text-center"><u>{{i.venue}}</u></button>
                </form>  
              </td>
              <td class="text-center align-middle">${{i.amount|floatformat:0|intcomma}}</td>               
              </tr>
              {% endfor %}
          </tbody>
    </table>
  </div>
</div>

{% endblock content %}

templates/svog/svog_state.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}
{% load humanize %}

{% block tags %}

<!-- Primary Meta Tags -->
<title>SVOG Dashboard</title>
<meta name="title" content="SVOG Dashboard">
<meta name="description" content="Shuttered Venue Operators Grantees">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://www.randoland.us/svog_state/">
<meta property="og:title" content="Wastebook: Shuttered Venue Operators Grants">
<meta property="og:description" content="Database of SVOG grantees">
<meta property="og:image" content="https://d3346f13f1pt3f.cloudfront.net/static/svog.png">

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:url" content="https://www.randoland.us/svog_state">
<meta name="twitter:title" content="Wastebook: Shuttered Venue Operators Grants">
<meta name="twitter:description" content="Database of SVOG grantees">
<meta name="twitter:image" content="https://d3346f13f1pt3f.cloudfront.net/static/svog.png">

{% endblock tags %}


{% block page_header %}

<div class="container-fluid">
  <div class="row">
  <div class="col-lg-6">
    <div class="text-left">
      <a href="{% url 'wastebooks:svog' %}">Dashboard Home</a>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="text-right">
      <a href = "https://data.sba.gov/dataset/svog">Data Source</a>
    </div>
  </div>
</div>
<div class="container-fluid text-center">
  <h2>Shuttered Venue Operators Grantees</h2>
</div>
{% endblock page_header %}  

{% block content %}
<style>
th {
  position: sticky;
  top: 0; /* Don't forget this, required for the stickiness */
}
</style>

<div class="container-fluid">

    <div class="row">
        <div class="col-auto">
          
          <form action="{% url 'wastebooks:svog_state' %}" method="post" id="inputState" >
          {% csrf_token %}
            <div class="form-group" style="max-width:200px">
              <label for="inputState" class="col-form-label col-form-label-sm">State/Territory:</label>
                <select class="form-control form-control-sm" name="inputState" id="inputState" onchange="this.form.submit()">
                  <option>{{state}}</option>
                  {% for i in state_list %}
                  <option>{{i}}</option>
                  {% endfor %}
                </select>
            </div>
          </form>
        
        </div>
      
      <div class="col-auto"> 
        <form method="post" action="{% url 'wastebooks:svog_city' %}" id="inputCity">
            {% csrf_token %}
            <div class="form-group">
              <label for="inputCity" class="col-form-label col-form-label-sm">City:</label>
                    <select class="form-control form-control-sm" name="inputCity" id="inputCity" onchange="this.form.submit()">
                        <option class="text-center" value="" selected disabled>--select city--</option>
                        {% for i in city_list %}
                        <option value="{{i.city_id}}">{{i.city}}</option>
                        {% endfor %}
                    </select>
            </div>
        </form>
      </div>
      <div class="col-auto" style="max-width:300px"> 
        <form method="post" action="{% url 'wastebooks:svog_venue' %}" id="inputVenue" >
            {% csrf_token %}
            <div class="form-group" style="max-width:400px">
              <label for="inputVenue" class="col-form-label col-form-label-sm">Venue:</label>
                    <select class="form-control form-control-sm" name="inputVenue" id="inputVenue" onchange="this.form.submit()">
                        <option class="text-center" value="" selected disabled>--select venue--</option>
                        {% for i in venue_list_data %}
                        <option value="{{i.inst_id}}">{{i.venue}}</option>
                        {% endfor %}
                    </select>
            </div>
        </form>
      </div>
    </div>
</div>


  <div class="border-bottom"></div>


  <div class="text-center container-fluid pt-2">
    <h2>{{state}} SVOG Data</h2> 
  </div>
  
  <div class="pb-2 container-fluid text-center" style="max-width:500px;">      
    
      <table class="m-auto text-center mt-2 table table-bordered">
        <tbody class="thead-dark">
          <tr class="table-active">
            <th scope="row" class="align-middle">Total</th>
            <td class="text-center align-middle"><b>${{state_total|floatformat:0|intcomma}}</b></td>               
          </tr>
          <tr class="table-active">
            <th scope="row" class="align-middle">Recipients</th>
            <td class="text-center align-middle"><b>{{total_grantees|floatformat:0|intcomma}}</b></td>               
          </tr>
          <tr class="table-active">
            <th scope="row" class="align-middle">Share of total</th>
            <td class="text-center align-middle"><b>{{percent_share|floatformat:1}}%</b></td>               
          </tr>
        </tbody>
      </table>
    
  </div>
  
  <div class="container-fluid pt-2 text-center">
    <div class="row text-center pt-2">
      <div class="col-lg-6">
        <div class="text-center container-fluid pt-2">
          <h4>Payouts by City</h4> 
        </div>
        <div class="container-fluid text-center" style="max-height: 500px;overflow:scroll;overflow-x:hidden;">
          <table class="text-center table table-sm table-bordered">
            <thead class="thead-dark">
              <tr>
                <th class="text-center" scope="col">City</th>
                <th scope="col">Total Grants</th>
              </tr>
            </thead>
            <tbody>
              {% for i in data %}
              <tr>
                <td class="text-center align-middle">
                  <form action="{% url 'wastebooks:svog_city' %}"  method="post">
                  {% csrf_token %}
                    <button type="submit" name="inputCity" value="{{i.city_id}}" class="btn btn-sm btn-light text-center"><u>{{i.city}}</button>
                  </form>  
                  </td>
                <td class="text-center align-middle">${{i.total|floatformat:0|intcomma}}</td>               
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>    
      <div class="col-lg-6" >
        <div class="text-center container-fluid pt-2">
          <h4>Payouts by Venue</h4> 
        </div>
        <div class="container-fluid text-center" style="max-height: 500px;overflow:scroll;overflow-x:hidden;"> 
          
            <table class="text-center table table-sm table-bordered">
              <thead class="thead-dark">
                <tr>
                  <th class="text-center" scope="col">Venue</th>
                  
                  <th scope="col">Grant</th>
                </tr>
              </thead>
              <tbody>
                {% for i in top_25_data %}
                <tr>
                  <td class="text-center align-middle">
                    <form action="{% url 'wastebooks:svog_venue' %}"  method="post">
                      {% csrf_token %}
                      <button type="submit" name="inputVenue" value="{{i.inst_id}}" class="btn btn-sm btn-light text-center"><u>{{i.venue}}</u></button>
                    </form>  
                  </td>
                  <td class="text-center align-middle">${{i.amount|floatformat:0|intcomma}}</td>               
                </tr>
                {% endfor %}
              </tbody>
            </table>
          
        </div> 
      </div>
    </div>
  </div>
  
{% endblock content %}

templates/svog/svog_venue.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}
{% load humanize %}

{% block tags %}

<!-- Primary Meta Tags -->
<title>SVOG Dashboard</title>
<meta name="title" content="SVOG Dashboard">
<meta name="description" content="Shuttered Venue Operators Grantees">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://www.randoland.us/svog_venue/">
<meta property="og:title" content="Wastebook: Shuttered Venue Operators Grants">
<meta property="og:description" content="Database of SVOG grantees">
<meta property="og:image" content="https://d3346f13f1pt3f.cloudfront.net/static/svog.png">

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:url" content="https://www.randoland.us/svog_venue">
<meta name="twitter:title" content="Wastebook: Shuttered Venue Operators Grants">
<meta name="twitter:description" content="Database of SVOG grantees">
<meta name="twitter:image" content="https://d3346f13f1pt3f.cloudfront.net/static/svog.png">

{% endblock tags %}


{% block page_header %}

<div class="container-fluid">
  <div class="row">
  <div class="col-lg-6">
    <div class="text-left">
      <a href="{% url 'wastebooks:svog' %}">Dashboard Home</a>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="text-right">
      <a href = "https://data.sba.gov/dataset/svog">Data Source</a>
    </div>
  </div>
</div>
<div class="text-center container-fluid">
  <h2>Shuttered Venue Operators Grantees</h2>
</div>
{% endblock page_header %}

{% block content %}

<div class="container-fluid">
  <div class="row">
      <div class="col-auto">
        <div class="text-center">
        <form action="{% url 'wastebooks:svog_state' %}" method="post" id="inputState" >
        {% csrf_token %}
          <div class="form-group" style="max-width:200px">
            <label for="inputState" class="col-form-label col-form-label-sm">State/Territory:</label>
            <select class="form-control form-control-sm" name="inputState" id="inputState" onchange="this.form.submit()">
              <option>{{state}}</option>
              {% for i in state_list %}
              <option>{{i}}</option>
              {% endfor %}
            </select>
              </select>
          </div>
        </form>
      </div>
      </div>
    
    <div class="col-auto"> 
      <form method="post" action="{% url 'wastebooks:svog_city' %}" id="inputCity">
          {% csrf_token %}
          <div class="form-group" style="max-width:400px">
            <label for="inputCity" class="col-form-label col-form-label-sm">City:</label>
              <select class="form-control form-control-sm" name="inputCity" id="inputCity" onchange="this.form.submit()">
                <option>{{city_name}}</option>
                {% for i in city_list %}
                <option value="{{i.city_id}}">{{i.city}}</option>
                {% endfor %}
              </select>
          </div>
      </form>
    </div>
    <div class="col-auto" style="max-width:300px"> 
      <form method="post" action="{% url 'wastebooks:svog_venue' %}" id="inputVenue" >
          {% csrf_token %}
          <div class="form-group" style="max-width:400px">
            <label for="inputVenue" class="col-form-label col-form-label-sm">Venue:</label>
              <select class="form-control form-control-sm" name="inputVenue" id="inputVenue" onchange="this.form.submit()">
                <option>{{venue_name}}</option>
                {% for i in venue_list_data %}
                <option value="{{i.inst_id}}">{{i.venue}}</option>
                {% endfor %}
            </select>
          </div>
      </form>
    </div>
  </div>
</div>

<div class="border-bottom"></div>
  <div class="p-3 container">
    {% for i in venue_detail %}
    <div class="text-center">
      <h3>Grant Detail</h3>
    </div>
    
      <table class="m-auto text-center mt-2 table table-bordered" style="max-width:600px;">
        
            <tr>
              
            </tr>
      
        <tbody>
          <thead class="thead-dark">
            <tr class="table-active">
              <th scope="row" class="align-middle">Grantee</th>
              <td class="text-center align-middle"><b>{{i.venue}}</b></td>               
            </tr>
            <tr class="table-active">
                <th scope="row" class="align-middle">Grant Amount</th>
                <td class="text-center align-middle"><b>${{i.amount|floatformat:0|intcomma}}</b></td>               
            </tr>
            <tr class="table-active">
              <th scope="row" class="align-middle">Venue Type</th>
              <td class="text-center align-middle"><b>{{i.type}}</b></td>               
            </tr>
            <tr class="table-active">
                <th scope="row" class="align-middle">Address</th>
                <td class="text-center align-middle"><b>{{i.address}}<br>{{i.city}}, {{i.state}} {{i.zip}}</b></td>               
            </tr>
          </thead>      
        </tbody>
      </table>
    
    {% endfor %}
  </div>
</div>

{% endblock content %}